variables = {}
variables["ge2j_ge1t"] = [ 
	# 'runNumber', 
	# 'eventNumber',
	# 'channelNumber', 
	# 'mcWeight', 
	#'pvxp_n', 
	#'vxp_z', 
	# 'scaleFactor_PILEUP',
	# 'scaleFactor_ELE', 
	# 'scaleFactor_MUON', 
	# 'scaleFactor_BTAG',
	# 'scaleFactor_TRIGGER', 
	# 'scaleFactor_JVFSF', 
	# 'scaleFactor_ZVERTEX', 
	# 'trigE', 
	# 'trigM', 
	# 'passGRL', 
	# 'hasGoodVertex', 
	'met_et', 
	'met_phi',

	#leptons
	'lep_n',
	#'lep_truthMatched_0', 	
	#'lep_trigMatched_0', 
	'lep_pt_0', 
	'lep_eta_0', 
	'lep_phi_0', 
	'lep_E_0', 
	'lep_z0_0', 
	#'lep_charge_0', 
	#'lep_type_0', 
	#'lep_flag_0', 
	#'lep_ptcone30_0', 
	#'lep_etcone20_0', 
	#'lep_trackd0pvunbiased_0', 
	#'lep_tracksigd0pvunbiased_0',

	#jets
	'jet_n', 
	#'alljet_n',
	'jet_pt_0', 
	'jet_pt_1', 
	'jet_pt_2', 
	'jet_eta_0', 
	'jet_eta_1', 
	'jet_eta_2', 
	'jet_phi_0',
	'jet_phi_1',
	'jet_phi_2',
	'jet_E_0', 
	'jet_E_1', 
	'jet_E_2', 
	'jet_m_0', 
	'jet_m_1',
	'jet_m_2',
	'jet_jvf_0', 
	'jet_jvf_1',
	'jet_jvf_2',
	#'jet_trueflav_0', 
	#'jet_trueflav_1',
	#'jet_trueflav_2',
	#'jet_truthMatched_0', 
	#'jet_truthMatched_1', 
	#'jet_truthMatched_2', 
	'jet_SV0_0', 
	'jet_SV0_1',
	'jet_SV0_2',
	'jet_MV1_0',
	'jet_MV1_1',
	'jet_MV1_2',

	'W_mass'
]

all_variables = list(set( [v for key in variables for v in variables[key] ] ))